name: Check pull request

on: 
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: |
          touch file.txt
          git add file.txt
          git commit -m "Creating file"
          git push
