name: pull_request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: on_push
        run: |
          touch new_file.txt
          git add new_file.txt
          git commit -m "Adding new file"
          git push
